return {
  area      = { "roomAdded", "roomRemoved", "updateTick" },
  room      = {
    "updateTick",
    "ready",
    "npcLeave",
    "npcEnter",
    "playerLeave",
    "playerEnter",
    "spawn",
  },
  channel   = { "channelReceive" },
  character = {
    "attributeUpdate",
    "combatStart",
    "combatantAdded",
    "combatantRemoved",
    "combatEnd",
    "equip",
    "unequip",
    "followed",
    "unfollowed",
    "gainedFlollower",
    "lostFollower",
    "hit",
    "damaged",
    "effectAdded",
    "effectRemoved",
    "heal",
    "healed",
  },
  item      = { "updateTick", "spawn" },
  effect    = {
    "effectActivated",
    "effectDeactivated",
    "remove",
    "effectStacked",
    "effectRefreshed",
  },
  server    = { "startup", "shutdown" },
  heal      = { "heal", "healed" },
  metadata  = { "metadataUpdated" },
  npc       = { "updateTick", "enterRoom", "spawn" },
  player    = {
    "commandQueued",
    "enterRoom",
    "save",
    "saved",
    "updateTick",
    "questProgress",
    "questStart",
    "questTurnReady",
    "questComplete",
  },
  quest     = { "start", "turn-in-ready", "progress", "complete" },
}
